apiVersion: skaffold/v3
kind: Config
metadata:
  name: online-boutique
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    push: true
  platforms: ["linux/amd64"]
  
  artifacts:
    - image: adservice
      context: src/adservice
    - image: cartservice
      context: src/cartservice/src
    - image: checkoutservice
      context: src/checkoutservice
    - image: currencyservice
      context: src/currencyservice
    - image: emailservice
      context: src/emailservice
    - image: frontend
      context: src/frontend
    - image: loadgenerator
      context: src/loadgenerator
    - image: paymentservice
      context: src/paymentservice
    - image: productcatalogservice
      context: src/productcatalogservice
    - image: recommendationservice
      context: src/recommendationservice
    - image: shippingservice
      context: src/shippingservice

deploy:
  kubectl: {}

profiles:
  - name: local
    build:
        platforms: ["linux/amd64"]
        local:
          push: false
    manifests:
        kustomize:
          paths:
            - kustomize/base
  - name: staging
    manifests:
      kustomize:
        paths:
          - kustomize/environments/staging
  - name: production
    manifests:
      kustomize:
        paths:
          - kustomize/environments/production